### ISSUE TITLE
Indentation in function agrument docs

### ISSUE THREAD

**Issue by qnikst** [tweag/guides#3]
Style guide tells that haddocks for arguments should look like following:
```
send
  :: Socket -- ^ Connected socket
  -> ByteString -- ^ Data to send
  -> IO Int -- ^ Bytes sent
```
The problematic part is `::` on another line. I understand that this is adviced because `::` and `->` are aligned. But I suggest to change that for the following reasons:
1. This breaks an usability pattern, currently if you want to find a function definition you could grep for `functionname ::` and all uses of the function will be ignored.
2. In other places we style guide suggests to avoid alignment, but it seems that there are no other purpose here bug aligmnent.
3. It's possible to align first argument with 2 extra spaces if needed
4. This goes to the contrary with the most explicit style guides and implicitly used styles in other projects.

I'm rising this as an issue for discussion, because I may miss some rationale behind this requirement

**Comment by mboes** [comment]
1. You can use `^functionname` instead, or use a smart editor.
2. The style guide does not discourage alignment itself: it discourages content-sensitive alignments, which create more busy work to edit and more conflicts.
4. None that I'm aware of that specifically mandate `::` on the same line, though yes, it's a common occurrence to write things that way.

The basic rationale is, there's no other good way to obviate content-sensitive alignment.

**Comment by Fuuzetsu** [comment]
>You can use ^functionname instead, or use a smart editor.

One case where this doesn't work is if the definition is not at the start of the line. Think things inside TH blocks (`remotableDecl`). Though it's a minor comment and I wouldn't use this as an argument.

**Comment by qnikst** [comment]
Really, I'm OK with the search `^functionname, though I'd me more happy if guide allow:
```
something :: Foo
                 -> Bar
```
or
```
something :: 
       Foo
   -> Bar
```
where it's applicable.
