### ISSUE TITLE
Repository label colors: p2 looks less pressing than p3

### ISSUE THREAD

**Issue by Profpatsch** [tweag/guides#8]
Arguably, P3 has a more urgent color than P2:

![screenshot](https://user-images.githubusercontent.com/3153638/52432665-57d93c80-2b0b-11e9-8c41-714cd32e462a.png)

It should be made a bit less saturated (but still more than P4).

**Comment by mboes** [comment]
We use the name colors as Bazel itself. I'd keep it as-is for consistency and because pay-off looks too low to me.
